# -*- coding: utf-8 -*-
"""ATD3DPY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zjb-bM7CfvLoBKFRklAG-J_tBRasrLju
"""

print("Enter The Number Of Rows: ")
r = int(input())
print("Enter The Number Of Columns: ")
c = int(input())
print("Enter The Depth: ")
d = int(input())

Arr = [[[0 for _ in range(d)] for _ in range(c)] for _ in range(r)]

print("ROW COLUMN AND DEPTH INDICES START AT 0!")
print("Enter The Row Index: ")
RI = int(input())
print("Enter The Column Index: ")
CI = int(input())
print("Enter The Depth Index: ")
DI = int(input())

while not (0 <= RI < r and 0 <= CI < c and 0 <= DI < d):
    print("INVALID INDEX! Enter New Indices")
    RI = int(input())
    CI = int(input())
    DI = int(input())

Arr[RI][CI][DI] = 1

print("This IS your Array: ")
for i in range(r):
    for j in range(c):
        for n in range(d):
            print(Arr[i][j][n], end=" ")
        print()

print("Position Of The 1 is: ")
for i in range(r):
    for j in range(c):
        for n in range(d):
            if Arr[i][j][n] == 1:
                print(f"Target Was Found at: ({i},{j},{n})")

quit = False
while not quit:
    print("1: Pick A New 1 Position")
    print("2: QUIT!")
    print("CHOOSE ONE OF THE OPTIONS: ")
    Choice = int(input())

    if Choice == 1:
        print("Enter The Number Of Rows: ")
        r = int(input())
        print("Enter The Number Of columns: ")
        c = int(input())
        print("Enter The Depth: ")
        d = int(input())

        Arr = [[[0 for _ in range(d)] for _ in range(c)] for _ in range(r)]
        print("ROW COLUMN AND DEPTH INDICES START AT 0!")
        print("Enter The Row Index: ")
        RI = int(input())
        print("Enter The Column Index: ")
        CI = int(input())
        print("Enter The Depth Index: ")
        DI = int(input())

        while not (0 <= RI < r and 0 <= CI < c and 0 <= DI < d):
            print("INVALID INDEX! Enter New Indices")
            RI = int(input())
            CI = int(input())
            DI = int(input())

        Arr[RI][CI][DI] = 1

        print("This IS your Array: ")
        for i in range(r):
            for j in range(c):
                for n in range(d):
                    print(Arr[i][j][n], end=" ")
                print()
        print("Position Of The 1 is: ")
        for i in range(r):
            for j in range(c):
                for n in range(d):
                    if Arr[i][j][n] == 1:
                        print(f"Target Was Found at: ({i},{j},{n})")
    elif Choice == 2:
        quit = True
        print("Exiting The Program!")
    else:
        print("INVALID CHOICE! Pick Again")
2