# -*- coding: utf-8 -*-
"""SIMPLE_CALC2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N_811VTnjrj72maj0rOwrKcsL4UZY027
"""

quit_program = False


while not quit_program:

  print("1: Multipication")
  print("2: Divison ")
  print("3: Additon")
  print("4: Subtraction")
  print("5: Quit")

  choice = int(input())

  if choice == 1:

    mc = False

    while not mc:

      print("1: integer mult.")
      print("2: dec. mult.")

      print("3: QUIT MULT")
      c = int(input())

      if c == 1:

        print("Choose a integer to be the x value")
        x = int(input())
        print("Choose an integer to be the y value")
        y = int(input())

        z = x * y

        print("your z value is: ", z)

      elif c == 2:

        print("Choose a decimal to be your x value")
        x = float(input())
        print("Choose a decimal to be your y value")
        y = float(input())
        z = x * y
        print(" your z value is: ", z)

      elif c == 3:

        print("you are closing multiplcation tab")
        mc = True

      else:

        print("INVALID CHOICE")

  elif choice == 2:

    dc = False

    while not dc:

      print("1: Int Divison")
      print("2: Dec Divison")
      print("3: Quit Divison")
      c = int(input())

      if c == 1:

        print("division will be x / y!")
        print("Choose an Integer to be the x value")
        x = int(input())
        print("Choose an integer to be the y value")
        y = int(input())

        z = x / y
        print("Your z is: ", z)

      elif c == 2:

        print("Divison is x/y!")
        print("choose a decimal x vlaue")
        x = float(input())
        print("choose a decimal y value")
        y = float(input())
        z = x / y
        print("your z value is:", z)

      elif c == 3:

        print("QUITTING DIVISON!")
        dc = True

      else:

        print("INVALID INPUT")
  elif choice == 3:
    ad = False
    while not ad:

      print("1: integer addition")
      print("2: decimal addition")
      print("3: quit addition")

      c = int(input())

      if c == 1:
        print("input an x value")
        x = int(input())
        print("input a y value")
        y = int(input())

        z = x + y
        print("your z value is", z)

      if c == 2:

        print("input an x value")
        x = float(input())
        print("input a y value")
        y = float(input())

        z = x + y
        print("your z value is", z)

      elif c == 3:

        print("QUITTING ADDITION")
        ad = True

      else:
        print("INVALID CHOICE")

  elif choice == 4:

    sd = False

    while not sd:

      print("1: integer subtraction")
      print("2: Decimal subtraction")
      print("3: quit")

      c = int(input())

      if c == 1:

        print("format will be X - Y")
        print("input an x value")

        x = int(input())

        print("input a y value")
        y = int(input())

        z = x - y
        print("your z is ", z)

      elif c == 2:

        print("format will be X - Y")
        print("input an x value")

        x =  float(input())

        print("input a y value")
        y = float(input())

        z = x - y
        print("your z is ", z)

      elif c == 3:

        sd = True
        print("Quitting Subtraction")

      else:

        print("INVALID RESPONSE")


  elif choice == 5:

    print("!!YOU ARE CLOSING THE PROGRAM!!")
    quit_program = True

  else:

    print("INVALID OPTION")