# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QEsMIGZZz3b-t0ljz18M1u1lLFR5Rxtk
"""

import random

quit_program = False
Arr = None

while not quit_program:
    print("1: Create Array")
    print("2: Find 1 and Randomize 0")
    print("3: QUIT!")
    print("CHOOSE ONE OF THE OPTIONS: ")
    choice = int(input())

    if choice == 1:
        print("Enter The Number Of Rows: ")
        r = int(input())
        print("Enter The Number Of columns: ")
        c = int(input())
        print("Enter The Depth: ")
        d = int(input())
        Arr = [[[0 for _ in range(d)] for _ in range(c)] for _ in range(r)]

        RI = random.randint(0, r - 1)
        CI = random.randint(0, c - 1)
        DI = random.randint(0, d - 1)

        Arr[RI][CI][DI] = 1

    elif choice == 2:
        if Arr is None:
            print("Please create an array first.")
        else:
            # Find 1 and Randomize 0
            one_found = False
            old_indices = None
            for i in range(len(Arr)):
                for j in range(len(Arr[0])):
                    for k in range(len(Arr[0][0])):
                        if Arr[i][j][k] == 1:
                            old_indices = (i, j, k)
                            one_found = True
                            break
                    if one_found:
                        break
                if one_found:
                    break

            if not one_found:
                print("1 not found in the array.")
            else:
                # Randomly change one input to 0
                new_indices = old_indices
                while new_indices == old_indices:
                    new_indices = (random.randint(0, len(Arr) - 1), random.randint(0, len(Arr[0]) - 1),
                                   random.randint(0, len(Arr[0][0]) - 1))

                Arr[old_indices[0]][old_indices[1]][old_indices[2]] = 0
                Arr[new_indices[0]][new_indices[1]][new_indices[2]] = 1

                # Display array
                print("Array after randomizing:")
                for i in range(len(Arr)):
                    for j in range(len(Arr[0])):
                        for k in range(len(Arr[0][0])):
                            print(Arr[i][j][k], end=" ")
                        print()
                    print()

                # Find 1 position
                print("Position Of The 1 is: ")
                print("Target Was Found at: ", new_indices)

    elif choice == 3:
        quit_program = True
        print("Exiting The Program!")
    else:
        print("INVALID CHOICE! Pick Again")